"""empty message

Revision ID: c20f7638d45e
Revises: 
Create Date: 2021-02-07 23:36:43.045690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20f7638d45e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('author_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'anonymous_user', ['author_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'author_user_id')
    # ### end Alembic commands ###
